apiVersion: v1
kind: Pod
metadata: 
  name: etcd
spec: 
  hostNetwork: true
  volumes:
    - name: "ssl-certs"
      hostPath:
        path: "/usr/share/ca-certificates"
    - name: "etcd-datadir"
      hostPath:
        path: "/var/lib/etcd"
  containers: 
    - name: "etcd"
      image: "b.gcr.io/kuar/etcd:2.1.1"
      args: 
        - "--data-dir=/var/lib/etcd"
        - "--advertise-client-urls=http://node1.c.kuarlab.internal:2379"
        - "--listen-client-urls=http://node1.c.kuarlab.internal:2379"
        - "--listen-peer-urls=http://node1.c.kuarlab.internal:2380"
        - "--initial-advertise-peer-urls=http://node1.c.kuarlab.internal:2380"
        - "--initial-cluster-token=japan"
        - "--initial-cluster=node0=http://node0.c.kuarlab.internal:2380,node1=http://node1.c.kuarlab.internal:2380,node2=http://node2.c.kuarlab.internal:2380"
        - "--initial-cluster-state=new"
        - "--name=node1"
      volumeMounts:
        - mountPath: /var/lib/etcd
          name: "etcd-datadir"
